---
language: node_js

sudo: false

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "npm --version"

os:
  - osx
  - linux


install:
  - npm install
  - bower install

services:
  - couchdb

before_script:
  - curl -X PUT localhost:5984/employees
